import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Routerlayout from "@/components/layout/Routerlayout";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Worklyst",
  description: "Generated by create next app",
  icons: {
    icon: "/worklyst.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.variable} antialiased`}>
        <Routerlayout>{children}</Routerlayout>
      </body>
    </html>
  );
}
